### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by Gabylot** [tehruttiger/Stockpiler#56]
I have version 1.51b running currently. I tried updating. I installed the requirements exactly with the correct version numbers as in the requirements.txt. After compiling with auto-py-to-exe and starting stockpiler.exe, i get the following error message:

Traceback (most recent call last):
  File "Stockpiler.py", line 22, in <module>
ModuleNotFoundError: No module named 'pygetwindow'
[47012] Failed to execute script 'Stockpiler' due to unhandled exception!

If i run the script with "python Stockpiler.exe" after pip installing pygetwindow , i get the following error message:

Log file created: logs/Stockpiler-log-2023-12-02-031321.txt
Traceback (most recent call last):
  File "E:\Stockpiler-master\Stockpiler.py", line 202, in <module>
    for rowdata in csv_input:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 4415: invalid start byte

I am not a programmer myself. Thank you for your attention, stay foxy!

**Comment by Gabylot** [comment]
I do get the same error when downloading the Stockpiler.1.6.1b.zip that has the stockpiler.exe already included. 

Traceback (most recent call last):
  File "E:\STOCKP~3\Stockpiler.py", line 202, in <module>
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 4706: invalid start byte

**Comment by Gabylot** [comment]
I fixed it.

Replace

# Load contents of ItemNumbering.csv into items.data
# Adds all fields (columns) even though only a few are used
with open('ItemNumbering.csv', 'rt') as f_input:

with

# Load contents of ItemNumbering.csv into items.data
# Adds all fields (columns) even though only a few are used
with open('ItemNumbering.csv', 'rt', encoding='latin-1') as f_input:
